# 配置mybatis-plus
mybatis-plus:
  # 配置扫描xml
  mapper-locations: clathpath:**/xml/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.mybatisplus.bean
  global-config:
    # 逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
    username: root
    password: 123456
server:
  tomcat:
    uri-encoding: utf-8
  port: 8080
logging:
  level:
    com.example.mybatisplus: debug


